name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate localizations
      run: flutter gen-l10n
      
    - name: Run tests
      run: flutter test

  build-windows:
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate localizations
      run: flutter gen-l10n
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: pamuk-desktop-windows-x64
        path: build/windows/x64/runner/Release/
        retention-days: 7

  build-linux:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Enable Linux desktop
      run: flutter config --enable-linux-desktop
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate localizations
      run: flutter gen-l10n
      
    - name: Build Linux app
      run: flutter build linux --release
      
    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: pamuk-desktop-linux-x64
        path: build/linux/x64/release/bundle/
        retention-days: 7
